data = [  {    "question": "What is the binary representation of the decimal number 123?",    "options": [      "1111011",      "1111101",      "1111111",      "1111001"    ],    "correct_answer": "1111011"  },  {    "question": "How many different values can be represented by a single byte in binary format?",    "options": [      "16",      "32",      "64",      "128"    ],    "correct_answer": "256"  },  {    "question": "What is the hexadecimal representation of the binary number 11001011?",    "options": [      "C3",      "D3",      "E3",      "F3"    ],    "correct_answer": "C3"  },  {    "question": "Which of the following is NOT a binary operator?",    "options": [      "AND",      "OR",      "NOT",      "XOR"    ],    "correct_answer": "XOR"  },  {    "question": "What is the binary representation of the decimal number 100?",    "options": [      "1100100",      "1100110",      "1101000",      "1101010"    ],    "correct_answer": "1100100"  },  {    "question": "How many bits are required to represent the decimal number 1023?",    "options": [      "8",      "10",      "12",      "14"    ],    "correct_answer": "10"  },  {    "question": "What is the hexadecimal representation of the binary number 10101010?",    "options": [      "AA",      "BB",      "CC",      "DD"    ],    "correct_answer": "AA"  },  {    "question": "Which of the following is a valid binary number?",    "options": [      "101010101",      "101010102",      "101010103",      "101010104"    ],    "correct_answer": "101010101"  },  {    "question": "What is the binary representation of the decimal number 512?",    "options": [      "1000000000",      "1000000001",      "1000000010",      "1000000011"    ],    "correct_answer": "1000000000"  },  {    "question": "How many different values can be represented by a 4-bit binary number?",    "options": [      "4",      "8",      "16",      "32"    ],    "correct_answer": "16"  },  {    "question": "What is the hexadecimal representation of the binary number 11111111?",    "options": [      "FF",      "FE",      "FD",      "FC"    ],    "correct_answer": "FF"  },  {    "question": "Which of the following is a valid binary operator?",    "options": [      "AND",      "OR",      "NOT",      "All of the above"    ],    "correct_answer": "All of the above"  }] 


# Print each question with its options and the correct answer
for item in data:
    print(f"Question: {item['question']}")
    for i, option in enumerate(item['options'], 1):
        print(f"  Option {i}: {option}")
    print(f"Correct Answer: {item['correct_answer']}")
    print()  # Print a blank line for better readability