# Generated by Django 5.0.3 on 2024-06-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_careerinfo_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerInfo',
        ),
    ]
