# Generated by Django 4.0 on 2024-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_careerinfo_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=100)),
                ('fav', models.CharField(default='0', max_length=2)),
                ('seen', models.CharField(default='0', max_length=2)),
                ('title', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
