# Generated by Django 4.0 on 2024-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_notificationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGitRepos',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='none', max_length=400)),
                ('description', models.TextField(default='no description...')),
                ('github_link', models.URLField(blank=True)),
            ],
        ),
    ]
