# Generated by Django 4.0 on 2024-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_careerinfo_user_name_usergitrepos_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(default='none', max_length=1000)),
                ('content', models.TextField(default='no content...')),
                ('videolink', models.URLField(default='https://www.youtube.com/')),
            ],
        ),
    ]
