# Generated by Django 4.0 on 2024-06-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_usercourses_allcourses_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCareerDetailed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('careername', models.CharField(default='none', max_length=1000)),
                ('topic', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('duration', models.CharField(default='none', max_length=100)),
                ('date', models.CharField(default='none', max_length=100)),
                ('slug', models.CharField(default='none', max_length=100)),
                ('done', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MyCareerDisplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('careername', models.CharField(default='none', max_length=1000)),
                ('done', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MyCareerTaskDetailed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('careername', models.CharField(default='none', max_length=1000)),
                ('topic', models.TextField(default='none')),
                ('subtopic', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('duration', models.CharField(default='none', max_length=100)),
                ('date', models.CharField(default='none', max_length=100)),
                ('slug', models.CharField(default='none', max_length=100)),
                ('done', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
