# Generated by Django 4.0 on 2024-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_mycareerdetailed_mycareerdisplay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('careername', models.TextField(default='none')),
                ('description', models.TextField(default='none')),
                ('duration', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
