# Generated by Django 4.0 on 2024-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_myreccareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraeerSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('careername', models.CharField(default='none', max_length=1000)),
                ('skills', models.TextField(default='none')),
                ('reodmapURL', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('summary', models.TextField(default='none')),
            ],
        ),
    ]
