# Generated by Django 4.0 on 2024-06-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_craeersearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craeersearch',
            old_name='reodmapURL',
            new_name='roadmapURL',
        ),
    ]
