# Generated by Django 4.0 on 2024-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_rename_reodmapurl_craeersearch_roadmapurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='craeersearch',
            name='jobcontent',
            field=models.TextField(default='none'),
        ),
    ]
