# Generated by Django 4.0 on 2024-06-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_craeersearch_jobcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('ytlink', models.CharField(default='none', max_length=1000)),
                ('content', models.TextField(default='none')),
                ('question', models.TextField(default='none')),
                ('options', models.TextField(default='none')),
                ('correctanswer', models.TextField(default='none')),
                ('useranswer', models.TextField(default='none')),
                ('iscorrect', models.TextField(default='0')),
            ],
        ),
    ]
